services:
  api:
    container_name: dify-api
    networks:
      - default
      - ssrf_proxy_network
      - sandbox

  worker:
    networks:
      - default
      - ssrf_proxy_network
      - sandbox

  plugin_daemon:
    networks:
      - default
      - ssrf_proxy_network
      - sandbox

networks:
  sandbox:
    external: true
    name: sandbox
