# docker-compose.override.yaml
services:
  api:
    container_name: crawl-api
    networks:
      - default
      - dify_default
      - sandbox

networks:
  dify_default:
    external: true
  sandbox:
    external: true
