services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
    networks:
      - voicevox_default

networks:
  voicevox_default:
    driver: bridge

volumes:
  open-webui:
  langflow-data: